// SpaceSizer provider-routing MVP
function providerCta(){return `<section class="providerCta"><div><div class="eyebrow">Next step</div><h3>Ready to store or move your belongings?</h3><p>Use your SpaceSizer result to find suitable local providers.</p></div><div class="providerChoices"><button class="providerChoice storage" data-provider="storage"><span class="providerIcon">🏢</span><span><b>Find storage near me</b><small>Search local self-storage providers for your recommended size.</small></span><strong>→</strong></button><button class="providerChoice transport" data-provider="transport"><span class="providerIcon">🚐</span><span><b>Find a man & van</b><small>Search local transport providers for your suggested vehicle.</small></span><strong>→</strong></button></div><small class="providerFine">SpaceSizer is independent. Provider availability, pricing and suitability should be confirmed directly with the provider.</small></section>`}

const baseResult=result;
result=function(){return baseResult().replace('<div class="notice"><b>Estimate only.</b>',providerCta()+'<div class="notice"><b>Estimate only.</b>')}

function providerScreen(){let m=rec(st.access),v=van(m.sqft),kind=st.providerType||'storage',isStorage=kind==='storage';return `<section class="page providerPage"><div class="eyebrow">Find local providers</div><h2>${isStorage?'Find storage near you.':'Find a man & van near you.'}</h2><p class="sub">Your SpaceSizer recommendation will stay with you while you search.</p><div class="providerRecap"><div><small>Storage recommendation</small><b>${m.label}</b></div><div><small>Vehicle guide</small><b>${v[0]}</b></div></div><div class="panel providerPanel"><label class="providerLabel" for="providerPostcode">Your postcode</label><input id="providerPostcode" class="search providerPostcode" autocomplete="postal-code" placeholder="e.g. SW19 5BA" value="${esc(st.postcode||'')}"><p class="providerHelp">We use your postcode only to open relevant local search results. It is not saved by SpaceSizer.</p><button class="btn primary providerSearchBtn" data-a="provider-search">${isStorage?'Search local storage':'Search local man & van'}</button><button class="btn secondary providerSwitch" data-a="provider-switch">${isStorage?'I also need transport':'I also need storage'}</button></div><div class="providerSummary"><b>What to tell the provider</b><p>${isStorage?`SpaceSizer estimates that you need approximately <strong>${m.label}</strong> of storage.`:`SpaceSizer suggests a <strong>${v[0]}</strong> for this load.`}</p><button class="mini" data-a="copy-provider-summary">Copy recommendation</button></div><div class="notice"><b>Independent search.</b> SpaceSizer does not currently rank, endorse or guarantee the companies shown in external search results. Partner listings can be added later.</div></section>`}

const baseRender=render;
render=function(){back.classList.toggle('hidden',st.screen==='home');app.innerHTML=({home,boxes,catalog,presets,review,result,provider:providerScreen}[st.screen]||home)();bind()}

const baseBind=bind;
bind=function(){baseBind();document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>{st.providerType=b.dataset.provider;st.postcode=st.postcode||'';nav('provider')});let pc=document.getElementById('providerPostcode');if(pc)pc.oninput=e=>{st.postcode=e.target.value.toUpperCase()};document.querySelectorAll('[data-a="provider-search"]').forEach(b=>b.onclick=()=>{let pc=(st.postcode||'').trim();if(!pc)return alert('Enter your postcode first.');let m=rec(st.access),v=van(m.sqft),q=st.providerType==='transport'?`man and van ${pc} ${v[0]}`:`self storage ${pc} ${m.label}`;window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q),'_blank','noopener')});document.querySelectorAll('[data-a="provider-switch"]').forEach(b=>b.onclick=()=>{st.providerType=st.providerType==='storage'?'transport':'storage';render()});document.querySelectorAll('[data-a="copy-provider-summary"]').forEach(b=>b.onclick=()=>{let m=rec(st.access),v=van(m.sqft),txt=`SpaceSizer estimate\nStorage: ${m.label}\nSuggested vehicle: ${v[0]}\nSelected items: ${count()}\n\nEstimate only — final fit depends on item dimensions and packing.`;navigator.clipboard?navigator.clipboard.writeText(txt).then(()=>alert('Recommendation copied.')):prompt('Copy recommendation:',txt)})}

render();