// SpaceSizer provider-routing MVP
const PROVIDER_COUNTRIES=['United Kingdom','Ireland','United States','Canada','Australia','New Zealand','France','Germany','Spain','Portugal','Italy','Netherlands','Belgium','Switzerland','Austria','Denmark','Sweden','Norway','Finland','Poland','Czechia','Greece','Turkey','United Arab Emirates','South Africa','India','Singapore','Malaysia','Brazil','Mexico','Other'];
function countryOptions(){let current=st.country||'United Kingdom';return PROVIDER_COUNTRIES.map(c=>`<option value="${esc(c)}" ${c===current?'selected':''}>${esc(c)}</option>`).join('')}
function sqm(sqft){return (sqft*0.092903).toFixed(1)}
function transportTerm(country){if(['United Kingdom','Ireland'].includes(country))return'man and van';if(['Australia','New Zealand'].includes(country))return'removalist';if(['United States','Canada'].includes(country))return'moving company';return'moving service'}
const PARTNER_FEED='https://spacesizer-business-manager.duga1975.chatgpt.site/api/public-businesses';
function partnerContact(b){let actions=[];if(b.website)actions.push(`<a href="${esc(b.website)}" target="_blank" rel="noopener">Visit website</a>`);if(b.phone)actions.push(`<a href="tel:${esc(b.phone)}">Call</a>`);if(b.email)actions.push(`<a href="mailto:${esc(b.email)}">Email</a>`);return actions.join('')}
function partnerMatches(b){let location=(st.location||'').trim().toLowerCase();if(!location)return true;let terms=location.split(/[\\s,]+/).filter(x=>x.length>2);let coverage=(b.coverage||'').toLowerCase();return !terms.length||terms.some(term=>coverage.includes(term))||coverage.includes('nationwide')||coverage.includes('uk')}
async function loadLivePartners(){let host=document.getElementById('livePartners');if(!host)return;try{let response=await fetch(PARTNER_FEED,{headers:{accept:'application/json'}});if(!response.ok)throw new Error('feed');let data=await response.json();let partners=(data.businesses||[]).filter(partnerMatches);if(!partners.length){host.innerHTML='<div class="partnerEmpty"><b>No featured partners match this location yet.</b><span>You can still search all local providers below.</span></div>';return}host.innerHTML=`<div class="partnerHeading"><div><div class="eyebrow">Featured SpaceSizer partners</div><h3>Companies ready to help</h3></div><span>${partners.length} available</span></div><div class="partnerGrid">${partners.map(b=>`<article class="partnerCard"><div class="partnerAvatar">${esc(b.name.slice(0,2).toUpperCase())}</div><div><h4>${esc(b.name)}</h4><p>${esc(b.coverage||'Coverage available on request')}</p><small>${esc([b.services,b.vehicles].filter(Boolean).join(' · ')||'Moving services')}</small><div class="partnerActions">${partnerContact(b)}</div></div></article>`).join('')}</div>`}catch{host.innerHTML='<div class="partnerEmpty"><b>Featured partners are temporarily unavailable.</b><span>Use the local search below to continue.</span></div>'}}
function providerCta(){return `<section class="providerCta"><div><div class="eyebrow">Next step</div><h3>Ready to store or move your belongings?</h3><p>Use your SpaceSizer result to find suitable providers near you, wherever you are.</p></div><div class="providerChoices"><button class="providerChoice storage" data-provider="storage"><span class="providerIcon">🏢</span><span><b>Find storage near me</b><small>Search nearby self-storage providers for your recommended size.</small></span><strong>→</strong></button><button class="providerChoice transport" data-provider="transport"><span class="providerIcon">🚐</span><span><b>Find transport / movers</b><small>Search nearby moving or van services for your suggested load.</small></span><strong>→</strong></button></div><small class="providerFine">SpaceSizer is independent. Provider availability, pricing and suitability should be confirmed directly with the provider.</small></section>`}

const baseResult=result;
result=function(){return baseResult().replace('<div class="notice"><b>Estimate only.</b>',providerCta()+'<div class="notice"><b>Estimate only.</b>')}

function providerScreen(){let m=rec(st.access),v=van(m.sqft),kind=st.providerType||'storage',isStorage=kind==='storage';return `<section class="page providerPage"><div class="eyebrow">Find local providers</div><h2>${isStorage?'Find storage near you.':'Find transport near you.'}</h2><p class="sub">Enter your country and location. Your SpaceSizer recommendation will stay with you while you search.</p><div class="providerRecap"><div><small>Storage recommendation</small><b>${m.label} <span class="metric">(${sqm(m.sqft)} m²)</span></b></div><div><small>Vehicle guide</small><b>${v[0]}</b></div></div><div id="livePartners" class="livePartners"><div class="partnerEmpty"><b>Loading featured partners…</b></div></div><div class="panel providerPanel"><div class="providerLocationGrid"><div><label class="providerLabel" for="providerCountry">Country</label><select id="providerCountry" class="providerSelect">${countryOptions()}</select></div><div><label class="providerLabel" for="providerLocation">Town, city, postcode or ZIP code</label><input id="providerLocation" class="search providerLocation" autocomplete="postal-code" placeholder="e.g. London, SW19 5BA, 10001" value="${esc(st.location||'')}"></div></div><p class="providerHelp">Your location is used only to open relevant local search results and is not saved by SpaceSizer.</p><button class="btn primary providerSearchBtn" data-a="provider-search">${isStorage?'Search local storage':'Search local transport'}</button><button class="btn secondary providerSwitch" data-a="provider-switch">${isStorage?'I also need transport':'I also need storage'}</button></div><div class="providerSummary"><b>What to tell the provider</b><p>${isStorage?`SpaceSizer estimates that you need approximately <strong>${m.label} (${sqm(m.sqft)} m²)</strong> of storage.`:`SpaceSizer suggests a <strong>${v[0]}</strong> for this load.`}</p><button class="mini" data-a="copy-provider-summary">Copy recommendation</button></div><div class="notice"><b>Independent search.</b> SpaceSizer does not currently rank, endorse or guarantee the companies shown in external search results. Partner listings can be added later.</div></section>`}

const baseRender=render;
render=function(){back.classList.toggle('hidden',st.screen==='home');app.innerHTML=({home,boxes,catalog,presets,review,result,provider:providerScreen}[st.screen]||home)();bind();if(st.screen==='provider'&&st.providerType==='transport')loadLivePartners()}

const baseBind=bind;
bind=function(){baseBind();document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>{st.providerType=b.dataset.provider;st.country=st.country||'United Kingdom';st.location=st.location||'';nav('provider')});let loc=document.getElementById('providerLocation');if(loc)loc.oninput=e=>{st.location=e.target.value};let country=document.getElementById('providerCountry');if(country)country.onchange=e=>{st.country=e.target.value};document.querySelectorAll('[data-a="provider-search"]').forEach(b=>b.onclick=()=>{let location=(st.location||'').trim(),country=st.country||'United Kingdom';if(!location)return alert('Enter your town, city, postcode or ZIP code first.');let m=rec(st.access),v=van(m.sqft),term=transportTerm(country),q=st.providerType==='transport'?`${term} ${location} ${country} ${v[0]}`:`self storage ${location} ${country} ${m.label}`;window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q),'_blank','noopener')});document.querySelectorAll('[data-a="provider-switch"]').forEach(b=>b.onclick=()=>{st.providerType=st.providerType==='storage'?'transport':'storage';render()});document.querySelectorAll('[data-a="copy-provider-summary"]').forEach(b=>b.onclick=()=>{let m=rec(st.access),v=van(m.sqft),txt=`SpaceSizer estimate\nStorage: ${m.label} (${sqm(m.sqft)} m²)\nSuggested vehicle: ${v[0]}\nSelected items: ${count()}\nLocation: ${(st.location||'Not entered')}, ${st.country||'United Kingdom'}\n\nEstimate only — final fit depends on item dimensions and packing.`;navigator.clipboard?navigator.clipboard.writeText(txt).then(()=>alert('Recommendation copied.')):prompt('Copy recommendation:',txt)})}

render();